using UnityMVC;
using UnityMVC.Model;

/* Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing. */
public partial class ContainerTemplate : Container
{
    private LoaderTemplate Loader => _loader;
    public void Initialize()
    {
        if (_loader != null)
        {
            return;
        }

        _loader = MVCApplication.Loaders.Get<LoaderTemplate>();
    }
}