using System;
using UnityEngine;
using UnityMVC.Controller;
using UnityMVC.View;


/// Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing.
public partial class ControllerTemplate : Controller
{
    public override void SetView(View view)
    {
        if (_view != null)
        {
            Debug.LogException(new Exception($"More than one View are trying to access {this.GetType()}"));
            return;
        }
        _view = view as ViewTemplate;
    }

    protected override void InternalAwake()
    {
        RegisterEvents();
        _events.onControllerInitialized?.Invoke(this);
    }
    protected override void InternalOnDestroy()
    {
        _events.onControllerDestroyed?.Invoke(this);
        UnregisterEvents();
    }
}
