using UnityMVC.Component;

/// Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing.
public partial class MVCComponentTemplate : MVCComponent
{
    protected override void InternalStart()
    {
        RegisterEvents();
        _events.onCreated?.Invoke();
    }
    protected override void InternalOnDestroy()
    {
        _baseView.UnregisterComponentFromView(this);
        UnregisterEvents();
        _events.onDestroyed?.Invoke();
    }
}