using UnityMVC;
using UnityMVC.View;

/// Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing.
public partial class InheritedView : BaseView
{
    protected override void LocateController()
    {
        _controller = MVCApplication.Controllers.Get<InheritedController>();
    }
    
    protected override void InternalAwake()
    {
        _controller.SetView(this);
        _controller.OnViewAwake();
    }
    protected override void InternalStart()
    {
        RegisterControllerEvents();
        StartCoroutine(LateStartRoutine());
    }
    protected override void InternalOnDestroy()
    {
        _events.onViewDestroyed?.Invoke(this);
        UnregisterControllerEvents();
    }
    
    protected override void ControllerStart()
    {
        _controller.OnViewStart();
    }
    protected override void ControllerUpdate()
    {
        _controller.OnViewUpdate();
    }
    protected override void ControllerOnEnable()
    {
        _controller.OnViewOnEnable();
    }
    protected override void ControllerOnDisable()
    {
        _controller.OnViewOnDisable();
    }
    protected override void ControllerOnDestroy()
    {
        _controller.OnViewDestroy();
    }
}