using UnityMVC.Model;
/*<NAMESPACE>*/
    //// Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing.
    public partial class ContainerTemplate : Container
    {
        private LoaderTemplate Loader => _loader;
        private LoaderTemplate _loader = new LoaderTemplate();
    }
/*}*/